[GLOBAL]
backend_packages = [
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",
  "pants.backend.shell",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.shell.lint.shellcheck"
]
pants_version = "2.14.0"

[anonymous-telemetry]
enabled = true
repo_id = "973c7138-724b-4cf5-9441-2cfc8e042668"

[docker]
build_args = ["GIT_TAG"]
default_repository = "chronicc/{name}"
env_vars = [
  "HOME",
  "USER",
  "DOCKER_CONFIG=%(homedir)s/.docker",
  "DOCKER_CONTEXT",
]
tools = [
  "docker-credential-secretservice",
  "dirname",
  "readlink",
  "python3",
]

[docker.registries.index]
address = "index.docker.io"
default = true

# [stats]
# log = true
