#!/usr/bin/env bash
# mise description="Run the container image"
# mise depends=["build"]

GIT_TAG=$1
if [ -z "$GIT_TAG" ]; then
  GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
fi

echo "Running image with tag: $GIT_TAG"

docker run -it --rm -v .:/repo chronicc/cloudbox:$GIT_TAG bash
