name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1

      - name: Fetch repository tags
        run: |
          git fetch --unshallow --tags

      - name: Run Make target 'test'
        run: |
          make test
